### ISSUE TITLE
Allow emojis to be filtered using apply_filters

### ISSUE THREAD

**Issue by neverything** [dol-lab/emoji-reactions#10]
Just an idea. I usually like having hooks and filters in all the right places. Before we have a complete admin page to add more emojis, it would be useful to have a simple filter for this array: https://github.com/dol-lab/emoji-reaction/blob/master/includes/class-emoji-reaction.php#L238-L244

**Comment by tillmariajuergens** [comment]
I added an element to the argument array of the filter `emoji_reaction_buttons` to enable a custom emoji list as long as we don't have an admin page. See https://github.com/dol-lab/emoji-reaction/commit/204204a41d5241a5cdc1ea79b4acf1142cd573b4

Or would you prefer an own specific filter?

**Comment by neverything** [comment]
This is perfect for now! Thank you very much!

**Comment by tillmariajuergens** [comment]
changed this to a filter. see readme.
