### ISSUE TITLE
Change interface for themes from filter to function

### ISSUE THREAD

**Issue by tillmariajuergens** [dol-lab/emoji-reactions#14]
A request was to change the plugin call from the filter to a function.

**Comment by schuhwerk** [comment]
What is this about?

**Comment by tillmariajuergens** [comment]
Actually it was your request to not use a filter to display the buttons in a theme and using a function instead.

**Comment by schuhwerk** [comment]
More context: https://github.com/dol-lab/spaces/blob/master/web/app/themes/defaultspace/inc/plugin-customizations/defaultspace-emoji-reaction.php#L15

**Comment by tillmariajuergens** [comment]
https://github.com/dol-lab/emoji-reaction/commit/f492d30ad8e70ed471315047a6f9e3dafcd3da34
