### ISSUE TITLE
Return a 401 instead of 500 error when nonce verification fails

### ISSUE THREAD

**Issue by neverything** [dol-lab/emoji-reactions#9]
Just a small thing, I would send a 401 instead of a 500 error:

https://github.com/dol-lab/emoji-reaction/blob/master/public/class-emoji-reaction-public.php#L132-L134

**Comment by schuhwerk** [comment]
Isn't [wp_send_json_error](https://developer.wordpress.org/reference/functions/wp_send_json_error/) meant for this?

**Comment by tillmariajuergens** [comment]
fixed: https://github.com/dol-lab/emoji-reaction/commit/669afa671c6c72426a4e9cf5fb2a644d908a8075
